"""Export experiment rows to course-required input/output/reference JSON files.

The experiment result files keep rich metadata for analysis. This script produces
plain files that are easier for course checking scripts and manual inspection:

- input.json: question + RAG context for each sample
- output.json: answer generated by one selected method
- reference.json: gold answer for the same sample ids
- output_<method>.json: per-method outputs when multiple methods exist
- output_all_methods.json: all method outputs in one table
"""
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.utils import read_json, write_json


def _latest_result(pattern: str) -> Path:
    files = sorted((ROOT / "experiments" / "results").glob(pattern))
    if not files:
        raise FileNotFoundError(f"no result file matched: {pattern}")
    return files[-1]


def _rows_by_method(data: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for block in data.get("results", []):
        method = block.get("condition", {}).get("method", "")
        for row in block.get("rows", []):
            grouped[str(row.get("method") or method)].append(row)
    return dict(grouped)


def _best_method(data: dict[str, Any], grouped: dict[str, list[dict[str, Any]]]) -> str:
    best_method = ""
    best_score = float("-inf")
    for block in data.get("results", []):
        method = str(block.get("condition", {}).get("method", ""))
        score = block.get("summary", {}).get("token_f1")
        if isinstance(score, (int, float)) and score > best_score:
            best_score = float(score)
            best_method = method
    if best_method:
        return best_method
    if not grouped:
        raise ValueError("result file contains no rows")
    return sorted(grouped)[0]


def _record_id(row: dict[str, Any]) -> int | str:
    return row.get("sample_id", row.get("id", ""))


def _context_text(row: dict[str, Any]) -> str:
    docs = row.get("docs") or []
    return "\n\n".join(f"[D{i + 1}] {doc}" for i, doc in enumerate(docs))


def _input_row(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": _record_id(row),
        "question": row.get("query", ""),
        "context": _context_text(row),
        "documents": row.get("docs") or [],
        "document_labels": row.get("labels") or [],
        "noise_ratio": row.get("noise_ratio_target", row.get("noise_ratio")),
        "noise_type": row.get("noise_type"),
        "noise_position": row.get("noise_position"),
    }


def _reference_row(row: dict[str, Any]) -> dict[str, Any]:
    gold = row.get("gold") or []
    answer = gold[0] if len(gold) == 1 else gold
    return {"id": _record_id(row), "answer": answer, "answers": gold}


def _output_row(row: dict[str, Any], *, include_method: bool = False) -> dict[str, Any]:
    out = {"id": _record_id(row), "answer": row.get("prediction", "")}
    if include_method:
        out["method"] = row.get("method", "")
    return out


def export_standard_files(
    result_path: Path,
    out_dir: Path,
    *,
    method: str | None = None,
) -> dict[str, Any]:
    data = read_json(result_path)
    grouped = _rows_by_method(data)
    selected_method = method or _best_method(data, grouped)
    if selected_method not in grouped:
        raise ValueError(
            f"method {selected_method!r} not in result file; available: {sorted(grouped)}"
        )

    selected_rows = sorted(grouped[selected_method], key=_record_id)
    input_rows = [_input_row(row) for row in selected_rows]
    reference_rows = [_reference_row(row) for row in selected_rows]
    output_rows = [_output_row(row) for row in selected_rows]

    write_json(input_rows, out_dir / "input.json")
    write_json(output_rows, out_dir / "output.json")
    write_json(reference_rows, out_dir / "reference.json")

    all_outputs: list[dict[str, Any]] = []
    for method_name, rows in sorted(grouped.items()):
        rows = sorted(rows, key=_record_id)
        method_outputs = [_output_row(row) for row in rows]
        write_json(method_outputs, out_dir / f"output_{method_name}.json")
        all_outputs.extend(_output_row(row, include_method=True) for row in rows)
    write_json(sorted(all_outputs, key=lambda r: (r["id"], r["method"])), out_dir / "output_all_methods.json")

    metadata = {
        "source_result": str(result_path.relative_to(ROOT)),
        "experiment": data.get("experiment"),
        "timestamp": data.get("timestamp"),
        "git_commit": data.get("git_commit"),
        "selected_method": selected_method,
        "methods": sorted(grouped),
        "n_samples": len(input_rows),
        "format_note": (
            "input.json/output.json/reference.json follow the course-required "
            "id-question-context / id-answer schema; documents and labels are kept "
            "as extra fields for RAG noise analysis."
        ),
    }
    write_json(metadata, out_dir / "metadata.json")
    return metadata


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--result",
        type=Path,
        default=None,
        help="Experiment result JSON. Defaults to latest exp4 zh/main semantic result.",
    )
    parser.add_argument(
        "--method",
        default=None,
        help="Method to write as output.json. Defaults to the best token-F1 method.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Output directory. Defaults to data/processed/<result-stem>.",
    )
    args = parser.parse_args()

    result_path = args.result or _latest_result("exp4_existing_methods_zh_*main*.json")
    result_path = result_path if result_path.is_absolute() else (ROOT / result_path)
    out_dir = args.out_dir or (ROOT / "data" / "processed" / result_path.stem)
    out_dir = out_dir if out_dir.is_absolute() else (ROOT / out_dir)

    metadata = export_standard_files(result_path, out_dir, method=args.method)
    print(f"exported standard JSON files -> {out_dir}")
    print(f"selected_method={metadata['selected_method']} n={metadata['n_samples']}")


if __name__ == "__main__":
    main()
